/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ControllerDAO.JogadorDAO;
import ModelDTO.JogadorDTO;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class frmJogo extends javax.swing.JFrame {

    boolean jogador1 = true;
    boolean jogador2 = true;
    int jogandoAgora;
    int cont1;
    int cont2;
    String[][] btnPosicao = new String[3][3];
    String linha1, linha2, linha3;
    String diagonal1, diagonal2;
    String horizontal1, horizontal2, horizontal3;

    /**
     * Creates new form frmJogo
     */
    public frmJogo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblJogador1Nome = new javax.swing.JLabel();
        lblJogador2Nome = new javax.swing.JLabel();
        lblJogador1Score = new javax.swing.JLabel();
        lblJogador2Score = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJogador1Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJogador1Nome.setText("Jogador 1");

        lblJogador2Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJogador2Nome.setText("Jogador 2");

        lblJogador1Score.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJogador1Score.setText("0");

        lblJogador2Score.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJogador2Score.setText("0");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn4.setEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn8.setEnabled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn7.setEnabled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblJogador1Nome)
                                    .addComponent(lblJogador1Score, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJogador2Nome)
                                    .addComponent(lblJogador2Score, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMenu)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJogador1Nome)
                            .addComponent(lblJogador2Nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJogador1Score)
                            .addComponent(lblJogador2Score))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReiniciar)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnMenu))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new frmSelecaoJogador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new frmJogoPrincipal().setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn3.setText("X");
            btnPosicao[0][2] = "X";
        } else {
            btn3.setText("O");
            btnPosicao[0][2] = "O";
        }

        btn3.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn9.setText("X");
            btnPosicao[2][2] = "X";
        } else {
            btn9.setText("O");
            btnPosicao[2][2] = "O";
        }

        btn9.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn2.setText("X");
            btnPosicao[0][1] = "X";
        } else {
            btn2.setText("O");
            btnPosicao[0][1] = "O";
        }

        btn2.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn6.setText("X");
            btnPosicao[1][2] = "X";
        } else {
            btn6.setText("O");
            btnPosicao[1][2] = "O";
        }

        btn6.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn5.setText("X");
            btnPosicao[1][1] = "X";
        } else {
            btn5.setText("O");
            btnPosicao[1][1] = "O";
        }

        btn5.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn4.setText("X");
            btnPosicao[01][0] = "X";
        } else {
            btn4.setText("O");
            btnPosicao[1][0] = "O";
        }

        btn4.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn8.setText("X");
            btnPosicao[2][1] = "X";
        } else {
            btn8.setText("O");
            btnPosicao[2][1] = "O";
        }

        btn8.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn7.setText("X");
            btnPosicao[2][0] = "X";
        } else {
            btn7.setText("O");
            btnPosicao[2][0] = "O";
        }

        btn7.setEnabled(false);
        verificarVencedor();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        verificarVezJogador();
        if (this.jogandoAgora == 1) {
            btn1.setText("X");
            btnPosicao[0][0] = "X";
        } else {
            btn1.setText("O");
            btnPosicao[0][0] = "O";
        }

        btn1.setEnabled(false);
        verificarVencedor();


    }//GEN-LAST:event_btn1ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarJogo();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblJogador1Nome;
    private javax.swing.JLabel lblJogador1Score;
    private javax.swing.JLabel lblJogador2Nome;
    private javax.swing.JLabel lblJogador2Score;
    // End of variables declaration//GEN-END:variables

    public void recebeJogador(String jogador1, String jogador2) {
        lblJogador1Nome.setText(jogador1);
        lblJogador2Nome.setText(jogador2);
    }

    public void iniciarJogo() {
        btn1.setEnabled(Boolean.TRUE);
        btn2.setEnabled(Boolean.TRUE);
        btn3.setEnabled(Boolean.TRUE);
        btn4.setEnabled(Boolean.TRUE);
        btn5.setEnabled(Boolean.TRUE);
        btn6.setEnabled(Boolean.TRUE);
        btn7.setEnabled(Boolean.TRUE);
        btn8.setEnabled(Boolean.TRUE);
        btn9.setEnabled(Boolean.TRUE);
        btnIniciar.setEnabled(false);

    }

    public void verificarVezJogador() {
        if (jogador1 && jogador2) {
            this.jogandoAgora = 1;
            jogador1 = false;
            jogador2 = true;
        } else if (jogador1 && jogador2 == false) {
            this.jogandoAgora = 1;
            jogador1 = false;
            jogador2 = true;
        } else {
            this.jogandoAgora = 2;
            jogador1 = true;
            jogador2 = false;

        }
    }

    public void limparPosicao() {
        for (cont1 = 0; cont1 < 3; cont1++) {
            for (cont2 = 0; cont2 < 3; cont2++) {
                btnPosicao[cont1][cont2] = " ";
            }
        }
    }

    public void verificarVencedor() {
        linha1 = btnPosicao[0][0] + btnPosicao[0][1] + btnPosicao[0][2];
        linha2 = btnPosicao[1][0] + btnPosicao[1][1] + btnPosicao[1][2];
        linha3 = btnPosicao[2][0] + btnPosicao[2][1] + btnPosicao[2][2];

        horizontal1 = btnPosicao[0][0] + btnPosicao[1][0] + btnPosicao[2][0];
        horizontal2 = btnPosicao[0][1] + btnPosicao[1][1] + btnPosicao[2][1];
        horizontal3 = btnPosicao[0][2] + btnPosicao[1][2] + btnPosicao[2][2];

        diagonal1 = btnPosicao[0][0] + btnPosicao[1][1] + btnPosicao[2][2];
        diagonal2 = btnPosicao[0][2] + btnPosicao[1][1] + btnPosicao[2][0];

        if (linha1.equals("XXX") || linha2.equals("XXX") || linha3.equals("XXX")
                || horizontal1.equals("XXX") || horizontal2.equals("XXX")
                || horizontal3.equals("XXX") || diagonal1.equals("XXX")
                || diagonal2.equals("XXX")) {
            String jogador = lblJogador1Nome.getText();
            JOptionPane.showMessageDialog(null, "O JOGADOR " + jogador + " VENCEU!");

            String score;
            int intScore;
            score = lblJogador1Score.getText();
            intScore = Integer.parseInt(score);
            intScore++;
            score = Integer.toString(intScore);
            lblJogador1Score.setText(score);

            JogadorDTO objJogadorDTO = new JogadorDTO();
            objJogadorDTO.setNome(lblJogador1Nome.getText());
            JogadorDAO objJogadorDAO = new JogadorDAO();
            objJogadorDAO.adicionarScore(objJogadorDTO);

            reiniciar();

        } else if (linha1.equals("OOO") || linha2.equals("OOO") || linha3.equals("OOO")
                || horizontal1.equals("OOO") || horizontal2.equals("OOO")
                || horizontal3.equals("OOO") || diagonal1.equals("OOO")
                || diagonal2.equals("OOO")) {
            String jogador = lblJogador2Nome.getText();
            JOptionPane.showMessageDialog(null, "O JOGADOR " + jogador + " VENCEU!");

            String score;
            int intScore;
            score = lblJogador2Score.getText();
            intScore = Integer.parseInt(score);
            intScore++;
            score = Integer.toString(intScore);
            lblJogador2Score.setText(score);

            JogadorDTO objJogadorDTO = new JogadorDTO();
            objJogadorDTO.setNome(lblJogador2Nome.getText());
            JogadorDAO objJogadorDAO = new JogadorDAO();
            objJogadorDAO.adicionarScore(objJogadorDTO);

            reiniciar();
        }

    }

    public void reiniciar() {
        btn1.setText(" ");
        btn1.setEnabled(true);
        btn2.setText(" ");
        btn2.setEnabled(true);
        btn3.setText(" ");
        btn3.setEnabled(true);
        btn4.setText(" ");
        btn4.setEnabled(true);
        btn5.setText(" ");
        btn5.setEnabled(true);
        btn6.setText(" ");
        btn6.setEnabled(true);
        btn7.setText(" ");
        btn7.setEnabled(true);
        btn8.setText(" ");
        btn8.setEnabled(true);
        btn9.setText(" ");
        btn9.setEnabled(true);
        jogador1 = true;
        jogador2 = true;
        limparPosicao();
    }
}
